services:
  gds:
    stop_grace_period: 3s
    user: user
    build:
      context: .
      dockerfile: Dockerfile
      args:
          - HOST_UID=${HOST_UID:-1000}
          - HOST_GID=${HOST_GID:-1000}
          - progress=plain
    image: $FSW_IMG
    command: "fprime-gds -n --ip-port=$UPLINK_TARGET_PORT --tts-port=$DOWNLINK_TARGET_PORT --dictionary ./dict/FlightComputerTopologyAppDictionary.xml"
    working_dir: ${DEPLOYMENT_ROOT}/build-artifacts/Linux/FlightComputer/
    ports:
      - $GDB_PORT:5555
      - $DOWNLINK_TARGET_PORT:50050
      - $GDS_WEB_GUI_PORT:5000
      - $UPLINK_TARGET_PORT:50000
    volumes:
      - ${SCRIPT_DIR}:${FSW_WDIR}
    network_mode: host   # uses the host's network stack
    healthcheck:
      test: ["CMD-SHELL", "pgrep fprime-gds"]
      interval: 2s
      timeout: 3s
      retries: 25
      start_period: 3s
  fsw:
    stop_grace_period: 1s
    user: user
    build:
      context: .
      dockerfile: Dockerfile
      args:
          - HOST_UID=${HOST_UID:-1000}
          - HOST_GID=${HOST_GID:-1000}
          - progress=plain
    image: $FSW_IMG
    working_dir: ${FSW_WDIR}
    environment:
        - GEVENT_SUPPORT=True
        - HOST_UID=${HOST_UID:-1000}
        - HOST_GID=${HOST_GID:-1000}
        - UPLINK_TARGET_PORT=$UPLINK_TARGET_PORT
        - FPRIME_CONFIG_DIR=/fsw/config
    volumes:
      - ${SCRIPT_DIR}:${FSW_WDIR}
    ports:
      - "${GDB_PORT}:${GDB_PORT}"
      - $DOWNLINK_TARGET_PORT:50050
      - $GDS_WEB_GUI_PORT:5000
    network_mode: host
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_NICE
      # For gdbserver's addr space randomization
      - SYS_PTRACE
    ulimits:
      rtprio: 99
    healthcheck:
      test: ["CMD-SHELL", "pgrep FlightComputer"]
      interval: 2s
      timeout: 3s
      retries: 25
      start_period: 5s
    depends_on:
      gds:
        condition: service_healthy
        restart: true

  # extended service that leverages a host device
  fsw-with-device:
      extends: fsw
      devices:
        - "${DEVICE_PORT}:/dev/ttyACM0"
